#!/usr/bin/env zsh

##PROFILE ZSH
# zmodload zsh/zprof

# LOCALE
export LC_ALL=en_US.UTF-8

# Skip rest for non-interactive shells (cron, ssh-cmd, scripts).
[[ -o interactive ]] || return

setopt vi  # If EDITOR is set to vim, we have this for free
KEYTIMEOUT=1                # snappy <Esc> in vi mode
setopt interactive_comments # allow for comments in interactive shells


export ZSH_EVALCACHE_DIR=${ZSH_EVALCACHE_DIR:-"$HOME/.zsh-evalcache"}

# Source all the things ✨ — cache sheldon's generated script
_sheldon_cache="${XDG_CACHE_HOME:-$HOME/.cache}/sheldon.zsh"
_sheldon_cfg="${XDG_CONFIG_HOME:-$HOME/.config}/sheldon/plugins.toml"
if [[ ! -s $_sheldon_cache || $_sheldon_cfg -nt $_sheldon_cache ]]; then
    mkdir -p ${_sheldon_cache:h}
    sheldon source >| $_sheldon_cache
fi
source $_sheldon_cache
unset _sheldon_cache _sheldon_cfg

# $HOME/.local/bin already added by dot_profile.
if [ -d "/opt/nvim" ]; then
    path_push "/opt/nvim/bin"
fi

# Go env
export GO111MODULE=on

# not needed when using mise for go installs
# export GOPATH="$HOME/.go"
# if [ -d "$GOPATH" ]; then
#     path_push "$GOPATH/bin"
# fi

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=253"

## PURE PROMT
PURE_CMD_MAX_EXEC_TIME=2
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2 #for powerlevel10k

# # Right side prompt (for kubectl)
# _lineup=$'\e[1A'
# _linedown=$'\e[1B'
# _kutl='%F{blue}$ZSH_KUBECTL_PROMPT%f'
# RPROMPT=%{${_lineup}%}${_kutl}%{${_linedown}%}

## Characters included **will** be considered part of the word
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

##PROFILE ZSH
# zprof
