#!/bin/sh

[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# history
HISTFILE=~/.zsh_history

# source
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"
plug "$HOME/.config/zsh/autocompletions.zsh"
plug "$HOME/.config/zsh/keybindings.zsh"
plug "$HOME/.config/zsh/plugins/sanekeybindings.zsh"

# plugins
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "hlissner/zsh-autopair"
plug "zsh-users/zsh-syntax-highlighting"
plug "jeffreytse/zsh-vi-mode"
plug "zap-zsh/fzf"
plug "zap-zsh/exa"
plug "zsh-users/zsh-syntax-highlighting"

## This variable tells zsh which non-alphanumeric characters are part of a word
## (e.g for kill-word or backward-kill-word if '/' not in there, it will stop the deletion)
## More info: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ/91d647269f69f7357b0dafa0ce050003edfb1e92#other-problems
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Load asdf
. "$HOME/.asdf/asdf.sh"

# Load autojump
. /usr/share/autojump/autojump.sh

eval "$(starship init zsh)"
