npm = {
  packages = [
    "@agentclientprotocol/claude-agent-acp",
  ]
}

arch = { packages = [{ name = "zig" }] }

cargo = {
  packages = [
    {
      name = "fff-mcp",
      options = {
        git = "https://github.com/dmtrKovalenko/fff",
        binstall = false,
      }
    },
  ]
}

uv = {
  packages = [
    {
      name = "graphifyy",
      hooks = {
        after_install = [
          "sh",
          "-c",
          "graphify install && graphify cursor install"
        ]
      }
    }
  ]
}
