arch = {
  packages = [
    "base",
    "base-devel",
    "linux",
    "linux-firmware",
    "networkmanager",
    "zip",
    "gnupg",
    "pinentry",
    "pkgconf",
    "vim",
    "git",
    "curl",
    "wget",
    "gcc",
    "openssl",
    "python",
    "python-pip",
    "python-pipx",
    "python-evdev",
    "keyd",
    "cliphist",
    "nm-connection-editor",
    {
      name = "arch-audit",
      hooks = {
        after_sync = [
          "systemctl",
          "--user",
          "enable",
          "--now",
          "cve-check.timer"
        ]
      }
    },
  ]
}

apt = {
  packages = [
    "build-essential",
    "network-manager",
    "zip",
    "gnupg2",
    "pinentry-tty",
    "pinentry-curses",
    "pkg-config",
    "vim",
    "git",
    "curl",
    "wget",
    "gcc",
    "libssl-dev",
    "python3-dev",
    "python3-pip",
    "pipx",
    "python3-venv",
    "python3-virtualenv",
  ]
}

pipx = { packages = ["pre-commit"] }

mise = {
  packages = [
    "kubectl",
    "go",
    "terraform",
    { name = "node", options = { version = "lts" } },
  ]
}

cargo = { packages = ["difftastic", "matugen"] }
