arch = [
    "base",
    "base-devel",
    "linux",
    "linux-firmware",
    "networkmanager",
    "zip",
    "gnupg",
    "pinentry",
    "pkgconf",
    "vim",
    "git",
    "curl",
    "wget",
    "gcc",
    "openssl",
    "python-evdev",         # for niri's tab cycling script
    "keyd",                 # swap caps and esc
    "cliphist",
    "nm-connection-editor",
]

apt = [
    "build-essential",
    "network-manager",
    "zip",
    "gnupg2",
    "pinentry-tty",
    "pinentry-curses",
    "pkg-config",
    "vim",
    "git",
    "curl",
    "wget",
    "gcc",
    "libssl-dev",
]

mise = [
    "kubectl",
    "go",
    "terraform",
    { package = "node", options = { version = "lts" } },
]

cargo = ["difftastic"]
