arch = {
  packages = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "neovim",
    "ripgrep",
    "tmux",
    "go-yq",
    "jq",
  ]
}

apt = {
  packages = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    # "neovim", -- don't install, as it too out of date. Use mise for it instead
    "ripgrep",
    "tmux",
    "yq",
    "jq",
  ]
}

cargo = {
  packages = [
    "bat",
    "zoxide",
    "nu",
    "sheldon",
    "tree-sitter-cli",
    "fd-find",
    "eza",
    "tlrc",
    "tsql"
  ]
}

mise = { packages = ["fzf"] }

go = {
  packages = [
    "github.com/jesseduffield/lazygit",
    "github.com/cli/cli/v2/cmd/gh"
  ]
}

npm = {
  packages = [
    "@agentclientprotocol/claude-agent-acp",
  ]
}
