arch = {
  packages = [
    "kitty",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "neovim",
    "ripgrep",
    "tmux",
    "go-yq",
    "jq",
  ]
}

apt = {
  packages = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "neovim",
    "ripgrep",
    "tmux",
    "yq",
    "jq",
  ]
}

cargo = {
  packages = ["bat", "zoxide", "nu", "sheldon", "tree-sitter-cli", "fd-find", "eza"]
}

mise = {
  packages = ["fzf"]
}

go = {
  packages = ["github.com/jesseduffield/lazygit"]
}
