-- Bitbucket links. Pure URL extractors over fixture pr/comment _raw payloads.
package.loaded["config.my.diff.providers.bitbucket_links"] = nil
local links = require("config.my.diff.providers.bitbucket_links")

local function pr(payload) return { _raw = { links = payload or {} } } end
local function comment(payload) return { _raw = { links = payload or {} } } end

describe("bitbucket_links.diff", function()
  it("returns href when present", function()
    assert.equals("http://diff", links.diff(pr({ diff = { href = "http://diff" } })))
  end)
  it("returns empty string when missing", function()
    assert.equals("", links.diff(pr({})))
    assert.equals("", links.diff(nil))
    assert.equals("", links.diff({}))
  end)
end)

describe("bitbucket_links.comments", function()
  it("returns href when present", function()
    assert.equals("http://c", links.comments(pr({ comments = { href = "http://c" } })))
  end)
  it("returns empty string when missing", function()
    assert.equals("", links.comments(pr({})))
  end)
end)

describe("bitbucket_links.approve", function()
  it("reads links.approve.href", function()
    assert.equals("http://a", links.approve(pr({ approve = { href = "http://a" } })))
  end)
  it("falls back to links.approve when it is a bare string", function()
    assert.equals("http://a", links.approve(pr({ approve = "http://a" })))
  end)
  it("returns empty string when missing", function()
    assert.equals("", links.approve(pr({})))
  end)
end)

describe("bitbucket_links.request_changes", function()
  it("reads hyphenated key links['request-changes'].href", function()
    assert.equals("http://rc", links.request_changes(pr({ ["request-changes"] = { href = "http://rc" } })))
  end)
  it("falls back to underscore key links.request_changes", function()
    assert.equals("http://rc", links.request_changes(pr({ request_changes = "http://rc" })))
  end)
  it("returns empty string when neither is present", function()
    assert.equals("", links.request_changes(pr({})))
  end)
end)

describe("bitbucket_links.html", function()
  it("reads links.html.href", function()
    assert.equals("http://h", links.html(pr({ html = { href = "http://h" } })))
  end)
  it("falls back to pr.link.html", function()
    local p = pr({})
    p.link = { html = "http://h" }
    assert.equals("http://h", links.html(p))
  end)
  it("returns empty string when nothing present", function()
    assert.equals("", links.html(pr({})))
  end)
end)

describe("bitbucket_links.self (comment)", function()
  it("reads comment._raw.links.self.href", function()
    assert.equals("http://self", links.self(comment({ self = { href = "http://self" } })))
  end)
  it("returns empty string when missing", function()
    assert.equals("", links.self(comment({})))
    assert.equals("", links.self(nil))
    assert.equals("", links.self({}))
  end)
end)
