#:schema https://starship.rs/config-schema.json
"$schema" = 'https://starship.rs/config-schema.json'
format = """
$kubernetes\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$azure\
$cmd_duration $jobs $time\
$line_break\
$character"""


[fill]
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol$context(\($namespace\))]($style) '

[directory]
style = "blue"
truncation_length = 4
truncate_to_repo = false
read_only = " 󰌾"

[character]
success_symbol = "[➜](green)"
error_symbol = "[✖](red)"
vicmd_symbol = "[V](bold green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[azure]
disabled = false
format = '[$symbol\[($subscription)\]]($style) '






